services:
  - type: web
    name: shortify-api
    env: python
    plan: free
    rootDir: backend # your FastAPI lives here
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENV
        value: render
      - key: BASE_URL
        value: https://example.com # change to your Render URL after first deploy
      - key: DATABASE_URL
        fromDatabase:
          name: shortify-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: shortify-redis
          property: connectionString

  - type: redis
    name: shortify-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0 # permissive; tighten later

databases:
  - name: shortify-postgres
    databaseName: shortify
    plan: free
