services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: shortify-api:latest
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      ENV: dev
      BASE_URL: http://localhost:8000
      SECRET_KEY: change-me-please
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:8000
      POSTGRES_USER: shortify
      POSTGRES_PASSWORD: shortify
      POSTGRES_DB: shortify
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      DATABASE_URL: postgresql+psycopg2://shortify:shortify@db:5432/shortify
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: shortify
      POSTGRES_PASSWORD: shortify
      POSTGRES_DB: shortify
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortify -d shortify"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
